/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.unindra.simple_project.view;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class AnotherDataMahasiswaView extends javax.swing.JFrame {

    /**
     * Creates new form AnotherDataMahasiswaView
     */


    public AnotherDataMahasiswaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderRadioGroup = new ButtonGroup();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        tfNpm = new JTextField();
        tfNama = new JTextField();
        religionComboBox = new JComboBox<>();
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        readHobby = new JCheckBox();
        exerciseHobby = new JCheckBox();
        singingHobby = new JCheckBox();
        dancingHobby = new JCheckBox();
        coockingHobby = new JCheckBox();
        writingHobby = new JCheckBox();
        saveBtn = new JButton();
        editBtn = new JButton();
        deleteBtn = new JButton();
        exitBtn = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("NPM");

        jLabel2.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Agama");

        jLabel4.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Hobi");

        religionComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu" }));

        genderRadioGroup.add(jRadioButton1);
        jRadioButton1.setText("Laki-Laki");

        genderRadioGroup.add(jRadioButton2);
        jRadioButton2.setText("Perempuan");

        readHobby.setText("Membaca");

        exerciseHobby.setText("Olahraga");

        singingHobby.setText("Menyanyi");
        singingHobby.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                singingHobbyActionPerformed(evt);
            }
        });

        dancingHobby.setText("Menari");

        coockingHobby.setText("Memasak");

        writingHobby.setText("Menulis");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");

        exitBtn.setText("Exit");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addComponent(religionComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNama, GroupLayout.PREFERRED_SIZE, 334, GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNpm, GroupLayout.PREFERRED_SIZE, 299, GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(readHobby)
                                    .addComponent(exerciseHobby)
                                    .addComponent(singingHobby))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(writingHobby)
                                    .addComponent(coockingHobby)
                                    .addComponent(dancingHobby)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(saveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)
                        .addGap(18, 18, 18)
                        .addComponent(exitBtn)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNpm, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(religionComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(readHobby)
                    .addComponent(dancingHobby))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(exerciseHobby)
                    .addComponent(coockingHobby))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(singingHobby)
                    .addComponent(writingHobby))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(exitBtn))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singingHobbyActionPerformed(ActionEvent evt) {//GEN-FIRST:event_singingHobbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singingHobbyActionPerformed

    private void editBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox coockingHobby;
    private JCheckBox dancingHobby;
    private JButton deleteBtn;
    private JButton editBtn;
    private JCheckBox exerciseHobby;
    private JButton exitBtn;
    private ButtonGroup genderRadioGroup;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JCheckBox readHobby;
    private JComboBox<String> religionComboBox;
    private JButton saveBtn;
    private JCheckBox singingHobby;
    private JTextField tfNama;
    private JTextField tfNpm;
    private JCheckBox writingHobby;
    // End of variables declaration//GEN-END:variables
}
