///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package org.unindra.simple_project.view;
//
//import org.netbeans.lib.awtextra.AbsoluteConstraints;
//import org.netbeans.lib.awtextra.AbsoluteLayout;
//import org.unindra.simple_project.swing.ImagePanelV2;
//
//import javax.swing.*;
//import java.awt.*;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.awt.event.KeyAdapter;
//import java.awt.event.KeyEvent;
//
///**
// * @author user
// */
//public class Pertemuan5 extends javax.swing.JFrame {
//
//    /**
//     * Creates new form GradingFormView
//     */
//    public Pertemuan5() {
//        initComponents();
//        clearResult();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        formPanel = new JPanel();
//        taskGradeLabel = new JLabel();
//        midtermGradeLabel = new JLabel();
//        examGradeLabel = new JLabel();
//        tfTaskGrade = new JTextField();
//        tfMidtermGrade = new JTextField();
//        tffinalExamGrade = new JTextField();
//        calcBtn = new JButton();
//        clearBtn = new JButton();
//        jPanel1 = new JPanel();
//        resultValueLabel = new JLabel();
//        resultGradeLabel = new JLabel();
//        sadImage = new ImagePanelV2();
//        happyImage = new ImagePanelV2();
//
//        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
//        setMinimumSize(new Dimension(640, 480));
//        setSize(new Dimension(640, 480));
//        getContentPane().setLayout(new AbsoluteLayout());
//
//        taskGradeLabel.setText("Nilai Tugas");
//
//        midtermGradeLabel.setText("Nilai UTS");
//
//        examGradeLabel.setText("Nilai UAS");
//
//        tfTaskGrade.setText("0");
//        tfTaskGrade.addKeyListener(new KeyAdapter() {
//            public void keyPressed(KeyEvent evt) {
//                tfTaskGradeKeyPressed(evt);
//            }
//        });
//
//        tfMidtermGrade.setText("0");
//        tfMidtermGrade.addKeyListener(new KeyAdapter() {
//            public void keyPressed(KeyEvent evt) {
//                tfMidtermGradeKeyPressed(evt);
//            }
//        });
//
//        tffinalExamGrade.setText("0");
//        tffinalExamGrade.addKeyListener(new KeyAdapter() {
//            public void keyPressed(KeyEvent evt) {
//                tffinalExamGradeKeyPressed(evt);
//            }
//        });
//
//        calcBtn.setText("Hitung Nilai");
//        calcBtn.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent evt) {
//                calcBtnActionPerformed(evt);
//            }
//        });
//
//        clearBtn.setText("Clear");
//        clearBtn.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent evt) {
//                clearBtnActionPerformed(evt);
//            }
//        });
//
//        GroupLayout formPanelLayout = new GroupLayout(formPanel);
//        formPanel.setLayout(formPanelLayout);
//        formPanelLayout.setHorizontalGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .addGroup(formPanelLayout.createSequentialGroup()
//                .addGap(30, 30, 30)
//                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                    .addComponent(taskGradeLabel)
//                    .addComponent(midtermGradeLabel)
//                    .addComponent(examGradeLabel)
//                    .addComponent(calcBtn))
//                .addGap(20, 20, 20)
//                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                    .addComponent(clearBtn)
//                    .addComponent(tffinalExamGrade, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
//                    .addComponent(tfMidtermGrade, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
//                    .addComponent(tfTaskGrade, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE))
//                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        formPanelLayout.setVerticalGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .addGroup(formPanelLayout.createSequentialGroup()
//                .addGap(29, 29, 29)
//                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                    .addComponent(taskGradeLabel)
//                    .addComponent(tfTaskGrade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//                .addGap(18, 18, 18)
//                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                    .addComponent(midtermGradeLabel)
//                    .addComponent(tfMidtermGrade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//                .addGap(18, 18, 18)
//                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                    .addComponent(examGradeLabel)
//                    .addComponent(tffinalExamGrade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//                .addGap(37, 37, 37)
//                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                    .addComponent(calcBtn)
//                    .addComponent(clearBtn))
//                .addContainerGap(113, Short.MAX_VALUE))
//        );
//
//        getContentPane().add(formPanel, new AbsoluteConstraints(29, 26, -1, -1));
//
//        jPanel1.setLayout(new AbsoluteLayout());
//        jPanel1.add(resultValueLabel, new AbsoluteConstraints(97, 28, -1, -1));
//        jPanel1.add(resultGradeLabel, new AbsoluteConstraints(97, 56, -1, -1));
//
//        sadImage.setImage(new ImageIcon(getClass().getResource("/images/shocked.jpeg"))); // NOI18N
//
//        GroupLayout sadImageLayout = new GroupLayout(sadImage);
//        sadImage.setLayout(sadImageLayout);
//        sadImageLayout.setHorizontalGroup(sadImageLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .addGap(0, 100, Short.MAX_VALUE)
//        );
//        sadImageLayout.setVerticalGroup(sadImageLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .addGap(0, 100, Short.MAX_VALUE)
//        );
//
//        jPanel1.add(sadImage, new AbsoluteConstraints(70, 100, -1, -1));
//
//        happyImage.setImage(new ImageIcon(getClass().getResource("/images/happy.png"))); // NOI18N
//
//        GroupLayout happyImageLayout = new GroupLayout(happyImage);
//        happyImage.setLayout(happyImageLayout);
//        happyImageLayout.setHorizontalGroup(happyImageLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .addGap(0, 106, Short.MAX_VALUE)
//        );
//        happyImageLayout.setVerticalGroup(happyImageLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .addGap(0, 100, Short.MAX_VALUE)
//        );
//
//        jPanel1.add(happyImage, new AbsoluteConstraints(60, 100, -1, -1));
//
//        getContentPane().add(jPanel1, new AbsoluteConstraints(380, 50, 220, -1));
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void calcBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
//        calculateGrade();
//    }//GEN-LAST:event_calcBtnActionPerformed
//
//    private void clearBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
//        clearForm();
//        clearResult();
//    }//GEN-LAST:event_clearBtnActionPerformed
//
//    private void tfTaskGradeKeyPressed(KeyEvent evt) {//GEN-FIRST:event_tfTaskGradeKeyPressed
//        if (isKeyEnter(evt)) tfMidtermGrade.requestFocus();
//    }//GEN-LAST:event_tfTaskGradeKeyPressed
//
//    private void tfMidtermGradeKeyPressed(KeyEvent evt) {//GEN-FIRST:event_tfMidtermGradeKeyPressed
//        if (isKeyEnter(evt)) examGradeLabel.requestFocus();
//    }//GEN-LAST:event_tfMidtermGradeKeyPressed
//
//    private void tffinalExamGradeKeyPressed(KeyEvent evt) {//GEN-FIRST:event_tffinalExamGradeKeyPressed
//        if (isKeyEnter(evt)) calcBtn.requestFocus();
//    }//GEN-LAST:event_tffinalExamGradeKeyPressed
//
//    private boolean isKeyEnter(KeyEvent event) {
//        return event.getKeyCode() == KeyEvent.VK_ENTER;
//    }
//
//    private void clearResult() {
//        resultValueLabel.setVisible(false);
//        resultGradeLabel.setVisible(false);
//        sadImage.setVisible(false);
//        happyImage.setVisible(false);
//    }
//
//    private void clearForm() {
//        tfTaskGrade.setText("0");
//        tfMidtermGrade.setText("0");
//        tffinalExamGrade.setText("0");
//    }
//
//    private void calculateGrade() {
//        int task = Integer.parseInt(tfTaskGrade.getText());
//        int midterm = Integer.parseInt(tfMidtermGrade.getText());
//        int finalExam = Integer.parseInt(tffinalExamGrade.getText());
//
//        double result = 0.2 * task + 0.3 * midterm + 0.5 * finalExam;
//        setGrade(result);
//    }
//
//    private void setGrade(double result) {
//        resultValueLabel.setText("Nilai : " + result);
//
//        resultValueLabel.setVisible(true);
//        resultGradeLabel.setVisible(true);
//
//        if (result > 88) {
//            resultGradeLabel.setText("Grade A");
//            happyImage.setVisible(true);
//            sadImage.setVisible(false);
//        } else if (result > 74) {
//            resultGradeLabel.setText("Grade B");
//            happyImage.setVisible(true);
//            sadImage.setVisible(false);
//        } else if (result > 56) {
//            resultGradeLabel.setText("Grade C");
//            happyImage.setVisible(true);
//            sadImage.setVisible(false);
//        } else if (result > 45) {
//            resultGradeLabel.setText("Grade D");
//            happyImage.setVisible(false);
//            sadImage.setVisible(true);
//        } else {
//            resultGradeLabel.setText("Grade E");
//            happyImage.setVisible(false);
//            sadImage.setVisible(true);
//        }
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String[] args) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
//                 UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pertemuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new Pertemuan5().setVisible(true);
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private JButton calcBtn;
//    private JButton clearBtn;
//    private JLabel examGradeLabel;
//    private JPanel formPanel;
//    private ImagePanelV2 happyImage;
//    private JPanel jPanel1;
//    private JLabel midtermGradeLabel;
//    private JLabel resultGradeLabel;
//    private JLabel resultValueLabel;
//    private ImagePanelV2 sadImage;
//    private JLabel taskGradeLabel;
//    private JTextField tfMidtermGrade;
//    private JTextField tfTaskGrade;
//    private JTextField tffinalExamGrade;
//    // End of variables declaration//GEN-END:variables
//
//
//}
